[TLS]
ca_cert = ./src/certs/ca.crt 
client_cert = ./src/certs/client.crt
client_key = ./src/certs/client.key

[MQTT]
broker = 193.205.129.120
port = 8883
qos = 1
topic = S.H.M.

[influx2]
bucket = Seismic Monitoring
url = http://localhost:8086
org = univpm
token = ; Insert your InfluxDB token here
timeout = 10000
verify_ssl = False

[tags]
; Insert any default tags for InfluxDB

[sensors]
use_temperature = True
; List of sensors to be written into InfluxDB. Delete if you want to exclude a sensor
sensors = IU.ANMO.08., 
		  IU.ANMO.09.
