FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY . /app 

COPY requirements.txt /tmp/requirements.txt

RUN pip install -r requirements.txt

CMD ["python", "src/query.py"]



