{
 "title": "Seismic Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "IU.ANMO.08.BHZ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "acceleration",
     "query": "SELECT \"x\" *0.00000387596 FROM \"acceleration\" WHERE (\"sensor_id\"::tag = 'IU.ANMO.08.BHZ') AND $timeFilter",
     "select": [
      [
       { "params": [ "x" ], "type": "field" },
       { "params": [ "*0.00000387596" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.08.BHZ" }
     ]
    }
   ]
  },
  {
   "title": "IU.ANMO.25.BHZ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "measurement": "acceleration",
     "query": "SELECT \"x\" *0.00000387596 FROM \"acceleration\" WHERE (\"sensor_id\"::tag = 'IU.ANMO.08.BHZ') AND $timeFilter",
     "select": [
      [
       { "params": [ "x" ], "type": "field" },
       { "params": [ "*0.00000387596" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.25.BHZ" }
     ]
    }
   ]
  },
  {
   "title": "IU.ANMO.08.BHZ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "measurement": "acceleration",
     "query": "SELECT \"x\" *0.00000387596 FROM \"acceleration\" WHERE (\"sensor_id\"::tag = 'IU.ANMO.08.BHZ') AND $timeFilter",
     "select": [
      [
       { "params": [ "y" ], "type": "field" },
       { "params": [ "*0.00000387596" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.08.BHZ" }
     ]
    }
   ]
  },
  {
   "title": "IU.ANMO.25.BHZ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "measurement": "acceleration",
     "query": "SELECT \"x\" *0.00000387596 FROM \"acceleration\" WHERE (\"sensor_id\"::tag = 'IU.ANMO.08.BHZ') AND $timeFilter",
     "select": [
      [
       { "params": [ "y" ], "type": "field" },
       { "params": [ "*0.00000387596" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.25.BHZ" }
     ]
    }
   ]
  },
  {
   "title": "IU.ANMO.08.BHZ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "measurement": "acceleration",
     "query": "SELECT \"x\" *0.00000387596 FROM \"acceleration\" WHERE (\"sensor_id\"::tag = 'IU.ANMO.08.BHZ') AND $timeFilter",
     "select": [
      [
       { "params": [ "z" ], "type": "field" },
       { "params": [ "*0.00000387596" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.08.BHZ" }
     ]
    }
   ]
  },
  {
   "title": "IU.ANMO.25.BHZ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "measurement": "acceleration",
     "query": "SELECT \"x\" *0.00000387596 FROM \"acceleration\" WHERE (\"sensor_id\"::tag = 'IU.ANMO.08.BHZ') AND $timeFilter",
     "select": [
      [
       { "params": [ "z" ], "type": "field" },
       { "params": [ "*0.00000387596" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.25.BHZ" }
     ]
    }
   ]
  },
  {
   "title": "IU.ANMO.08.BHZ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.08.BHZ" }
     ]
    }
   ]
  },
  {
   "title": "IU.ANMO.25.BHZ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.25.BHZ" }
     ]
    }
   ]
  },
  {
   "title": "IU.ANMO.08.BHZ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "measurement": "acceleration",
     "query": "SELECT \"x\" *0.00000387596 FROM \"acceleration\" WHERE (\"sensor_id\"::tag = 'IU.ANMO.08.BHZ') AND $timeFilter",
     "select": [
      [
       { "params": [ "x" ], "type": "field" },
       { "params": [ "*0.00000387596" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.08.BHZ" }
     ]
    },
    {
     "measurement": "acceleration",
     "query": "SELECT \"x\" *0.00000387596 FROM \"acceleration\" WHERE (\"sensor_id\"::tag = 'IU.ANMO.08.BHZ') AND $timeFilter",
     "select": [
      [
       { "params": [ "y" ], "type": "field" },
       { "params": [ "*0.00000387596" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.08.BHZ" }
     ]
    },
    {
     "measurement": "acceleration",
     "query": "SELECT \"x\" *0.00000387596 FROM \"acceleration\" WHERE (\"sensor_id\"::tag = 'IU.ANMO.08.BHZ') AND $timeFilter",
     "select": [
      [
       { "params": [ "z" ], "type": "field" },
       { "params": [ "*0.00000387596" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.08.BHZ" }
     ]
    }
   ]
  },
  {
   "title": "IU.ANMO.25.BHZ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "measurement": "acceleration",
     "query": "SELECT \"x\" *0.00000387596 FROM \"acceleration\" WHERE (\"sensor_id\"::tag = 'IU.ANMO.08.BHZ') AND $timeFilter",
     "select": [
      [
       { "params": [ "x" ], "type": "field" },
       { "params": [ "*0.00000387596" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.25.BHZ" }
     ]
    },
    {
     "measurement": "acceleration",
     "query": "SELECT \"x\" *0.00000387596 FROM \"acceleration\" WHERE (\"sensor_id\"::tag = 'IU.ANMO.08.BHZ') AND $timeFilter",
     "select": [
      [
       { "params": [ "y" ], "type": "field" },
       { "params": [ "*0.00000387596" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.25.BHZ" }
     ]
    },
    {
     "measurement": "acceleration",
     "query": "SELECT \"x\" *0.00000387596 FROM \"acceleration\" WHERE (\"sensor_id\"::tag = 'IU.ANMO.08.BHZ') AND $timeFilter",
     "select": [
      [
       { "params": [ "z" ], "type": "field" },
       { "params": [ "*0.00000387596" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.25.BHZ" }
     ]
    }
   ]
  },
  {
   "title": "IU.ANMO.08.BHZ, IU.ANMO.09.BHZ, IU.ANMO.25.BHZ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 30 },
   "targets": [
    {
     "measurement": "acceleration",
     "select": [
      [
       { "params": [ "x" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.08.BHZ" }
     ]
    },
    {
     "measurement": "acceleration",
     "select": [
      [
       { "params": [ "x" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.09.BHZ" }
     ]
    },
    {
     "measurement": "acceleration",
     "select": [
      [
       { "params": [ "x" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.25.BHZ" }
     ]
    }
   ]
  },
  {
   "title": "IU.ANMO.08.BHZ, IU.ANMO.09.BHZ, IU.ANMO.25.BHZ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 39 },
   "targets": [
    {
     "measurement": "acceleration",
     "select": [
      [
       { "params": [ "y" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.08.BHZ" }
     ]
    },
    {
     "measurement": "acceleration",
     "select": [
      [
       { "params": [ "y" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.09.BHZ" }
     ]
    },
    {
     "measurement": "acceleration",
     "select": [
      [
       { "params": [ "y" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.25.BHZ" }
     ]
    }
   ]
  },
  {
   "title": "IU.ANMO.08.BHZ, IU.ANMO.09.BHZ, IU.ANMO.25.BHZ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 48 },
   "targets": [
    {
     "measurement": "acceleration",
     "select": [
      [
       { "params": [ "z" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.08.BHZ" }
     ]
    },
    {
     "measurement": "acceleration",
     "select": [
      [
       { "params": [ "z" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.09.BHZ" }
     ]
    },
    {
     "measurement": "acceleration",
     "select": [
      [
       { "params": [ "z" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_id::tag", "operator": "=", "value": "IU.ANMO.25.BHZ" }
     ]
    }
   ]
  }
 ]
}